version: "3"
services:
  akka-serverless-proxy:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.5
    command: -Dconfig.resource=dev-mode.conf
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8081}
      # Uncomment to disable the JWT dev secret
      # JWT_DEV_SECRET: "false"
      # Uncomment to set the JWT dev secret issuer
      # JWT_DEV_SECRET_ISSUER: "my-issuer"